# Change these first
owner: Xaradon # Your GitHub username
repo: D4OStatus # Your GitHub repository name

# Add your sites here
sites:
  - name: D4O Homepage
    url: https://d4o.de
  - name: Accounting
    url: https://accounting.d4o-free2play.de
  - name: D4O Wiki
    url: https://wiki.d4o.de/
  - name: Support System
    url: https://ticket.d4o.de/
 # - name: Test for HEAD
 #   method: HEAD
 #   url: https://www.google.com
 # - name: Secret Site
 #   url: $SECRET_SITE
 # - name: TCP ping
 #   url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: D4OStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: D4O Status
  introTitle: ""
  introMessage: Status der D4O Server
  navbar:
    - title: Status
      href: /
    - title: D4O Homepage
      href: https://d4o.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
